[pytest]
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning
    ignore:.*StarletteDeprecationWarning.*
    ignore:.*Using `httpx` with `starlette.testclient`.*
